#defines and runs multi-container Docker applications (entire system)
version: '3.8'

services:
  # Student-2
  student-2-backend:
    build:
      context: ./student-2/backend
      dockerfile: dockerfile
    ports:
      - "5002:5002"

  #  Agentic Loop
 # agentic-loop:
  #  build:
   #   context: ./agentic-loop
    #  dockerfile: Dockerfile  # Убедитесь, что этот файл существует в agentic-loop/
  