server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;


    # =================================================
    # SHARED HOMEPAGE
    # =================================================

    location = / {
        try_files /index.html =404;
    }


    # =================================================
    # ACCOUNT FRONTEND
    # =================================================

    location /account {
        proxy_pass http://account-frontend:80;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =================================================
    # ACCOMMODATION FRONTEND
    # =================================================

    location /accommodation/ {
        proxy_pass http://accommodation-frontend:3002/;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

        location = /attractions {
        return 301 /attractions/;
    }
    # =================================================
    # ATTRACTIONS FRONTEND
    # =================================================

    location /attractions/ {
        proxy_pass http://attractions-frontend:80;
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

     # =================================================
    # CHECKLIST FRONTEND
    # =================================================

    location = /checklist {
        return 301 /checklist/;
    }

    location /checklist/ {
        proxy_pass http://checklist-frontend:3004/;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =================================================
    # FLIGHT FRONTEND
    # =================================================

    location /flight/ {
        proxy_pass http://flight-frontend:80;

        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =================================================
    # SHARED API GATEWAY
    # =================================================

    location /api/ {
        proxy_pass http://shared-gateway:5000;

        proxy_http_version 1.1;

        proxy_read_timeout 120s;
        proxy_send_timeout 120s;


        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =================================================
    # SHARED STATIC FILES
    # =================================================

    location / {
        try_files $uri $uri/ /index.html;
    }
}