FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Добавляем /app в пути поиска модулей Python
ENV PYTHONPATH=/app

EXPOSE 5002

CMD ["python", "backend/app.py"]