SERVICES = {
    "account": {
        "name": "Customer Account / Profile Service",
        "student_id": "25992405",
        "architecture": {
            "frontend_service": "account-frontend", "backend_service": "account-backend",
            "frontend_type": "nginx", "frontend_port": 80, "database_port": 6001,
            "frontend_files": ["nginx.conf", "templates/login.html"],
            "database_url_key": "ACCOUNT_DATABASE_URL", "gateway_url_key": "ACCOUNT_BACKEND_URL",
            "home_link": "/account", "proxy_location": "/account",
        },
        "endpoints": {
            "base_url": "http://localhost:5001",
            "health_service": "account-backend",
            "health_status": "healthy",
            "checks": [
                {"path": "/api/account/session", "status": 200, "equals": {"authenticated": False, "customer_id": None}},
                {"path": "/api/account/profile", "status": 401, "error_required": True},
                {"path": "/api/account/preferences", "status": 401, "error_required": True},
            ],
        },
        "path": "student-25992405",
        "frontend_dir": "student-25992405/account-frontend",
        "backend_dir": "student-25992405/account-backend",
        "backend_path": "student-25992405/account-backend/app.py",
        "routes_dir": "student-25992405/account-backend/routes",
        "database_dir": "student-25992405/account-database",
        "schema_path": "student-25992405/account-database/schema.sql",
        "seed_path": "student-25992405/account-database/init.sql",
        "ci_pipeline": ".github/workflows/student-25992405-ci.yml",
        "database_service": "account-database",
        "container_db_path": "/data/account.db",
        "db_tables": {
            "customer": ["customer_id", "first_name", "last_name", "email", "password", "created_at"],
            "preference": ["preference_id", "customer_id"],
        },
    },
    "accommodation": {
        "name": "Accommodation Service",
        "student_id": "14649634",
        "architecture": {
            "frontend_service": "accommodation-frontend", "backend_service": "accommodation-backend",
            "frontend_type": "flask", "frontend_port": 3002, "database_port": 6002,
            "frontend_files": ["app.py", "templates/accommodation.html"],
            "database_url_key": "DATABASE_API_URL", "gateway_url_key": "ACCOMMODATION_BACKEND_URL",
            "home_link": "/accommodation/", "proxy_location": "/accommodation/",
        },
        "endpoints": {
            "base_url": "http://localhost:5002",
            "health_service": "accommodation-backend",
            "health_status": "ok",
            "list_path": "/api/accommodations",
            "id_field": "accommodation_id",
            "checks": [{"path": "/api/accommodations?max_price=invalid", "status": 400, "error_required": True}],
        },
        "path": "student-14649634",
        "frontend_dir": "student-14649634/accommodation-frontend",
        "backend_dir": "student-14649634/accommodation-backend",
        "backend_path": "student-14649634/accommodation-backend/app.py",
        "routes_dir": "student-14649634/accommodation-backend/routes",
        "database_dir": "student-14649634/accommodation-database",
        "schema_path": "student-14649634/accommodation-database/schema.sql",
        "seed_path": "student-14649634/accommodation-database/init.sql",
        "ci_pipeline": ".github/workflows/student-14649634-ci.yml",
        "database_service": "accommodation-database",
        "container_db_path": "/data/accommodation.db",
        "db_tables": {
            "accommodations": ["accommodation_id", "accommodation_name", "type", "city", "price_per_night", "guest_capacity"],
            "availability": ["availability_id", "accommodation_id", "date", "is_available"],
        },
    },
    "attractions": {
        "name": "Attractions & Tour Experiences",
        "student_id": "25693742",
        "architecture": {
            "frontend_service": "attractions-frontend", "backend_service": "attractions-backend",
            "frontend_type": "nginx", "frontend_port": 80, "database_port": 6003,
            "frontend_files": ["nginx.conf", "index.html"],
            "database_url_key": "DATABASE_API_URL", "gateway_url_key": "ATTRACTIONS_BACKEND_URL",
            "home_link": "/attractions/", "proxy_location": "/attractions/",
        },
        "endpoints": {
            "base_url": "http://localhost:5003",
            "health_service": "attractions-backend",
            "health_status": "ok",
            "list_path": "/api/attractions",
            "id_field": "attraction_id",
            "checks": [{"path": "/api/attractions?max_price=invalid", "status": 400, "error_required": True}],
        },
        "path": "student-25693742",
        "frontend_dir": "student-25693742/attractions-frontend",
        "backend_dir": "student-25693742/attractions-backend",
        "backend_path": "student-25693742/attractions-backend/app.py",
        "routes_dir": "student-25693742/attractions-backend/routes",
        "database_dir": "student-25693742/attractions-database",
        "schema_path": "student-25693742/attractions-database/schema.sql",
        "seed_path": "student-25693742/attractions-database/init.sql",
        "ci_pipeline": ".github/workflows/student-25693742-ci.yml",
        "database_service": "attractions-database",
        "container_db_path": "/data/attractions.db",
        "db_tables": {
            "attractions": ["attraction_id", "name", "category", "city", "price"],
            "reviews": ["review_id", "attraction_id", "rating"],
        },
    },
    "checklist": {
        "name": "Pre-Trip Checklist Service",
        "student_id": "14582668",
        "architecture": {
            "frontend_service": "checklist-frontend", "backend_service": "checklist-backend",
            "frontend_type": "flask", "frontend_port": 3004, "database_port": 6004,
            "frontend_files": ["app.py", "templates/checklist.html"],
            "database_url_key": "CHECKLIST_DATABASE_URL", "gateway_url_key": "CHECKLIST_BACKEND_URL",
            "home_link": "/checklist/", "proxy_location": "/checklist/",
        },
        "endpoints": {
            "base_url": "http://localhost:5004",
            "health_service": "checklist-backend",
            "health_status": "healthy",
            "list_path": "/api/checklist-items",
            "id_field": "item_id",
            "filters": [{"field": "item_type", "value": "task"}],
            "checks": [{"path": "/api/checklist-items?item_type=invalid", "status": 400, "error_required": True}],
        },
        "path": "student-14582668",
        "frontend_dir": "student-14582668/checklist-frontend",
        "backend_dir": "student-14582668/checklist-backend",
        "backend_path": "student-14582668/checklist-backend/app.py",
        "routes_dir": "student-14582668/checklist-backend/routes",
        "database_dir": "student-14582668/checklist-database",
        "schema_path": "student-14582668/checklist-database/schema.sql",
        "seed_path": "student-14582668/checklist-database/init.sql",
        "ci_pipeline": ".github/workflows/student-14582668-ci.yml",
        "database_service": "checklist-database",
        "container_db_path": "/data/checklist.db",
        "db_tables": {
            "checklist_items": ["item_id", "title", "item_type", "is_completed"],
        },
    },
    "flight": {
        "name": "Flight Service",
        "student_id": "25487036",
        "architecture": {
            "frontend_service": "flight-frontend", "backend_service": "flight-backend",
            "frontend_type": "nginx", "frontend_port": 80, "database_port": 6005,
            "frontend_files": ["nginx.conf", "templates/search.html"],
            "database_url_key": "FLIGHT_DATABASE_URL", "gateway_url_key": "FLIGHT_BACKEND_URL",
            "home_link": "/flight/search", "proxy_location": "/flight/",
        },
        "endpoints": {
            "base_url": "http://localhost:5005",
            "health_service": "flight-backend",
            "health_status": "healthy",
            "list_path": "/api/flight/flights",
            "id_field": "flight_id",
            "filters": [{"field": "origin"}, {"field": "destination"}],
            "checks": [],
        },
        "path": "student-25487036",
        "frontend_dir": "student-25487036/flight-frontend",
        "backend_dir": "student-25487036/flight-backend",
        "backend_path": "student-25487036/flight-backend/app.py",
        "routes_dir": "student-25487036/flight-backend/routes",
        "database_dir": "student-25487036/flight-database",
        "schema_path": "student-25487036/flight-database/schema.sql",
        "seed_path": "student-25487036/flight-database/init.sql",
        "ci_pipeline": ".github/workflows/student-25487036-ci.yml",
        "database_service": "flight-database",
        "container_db_path": "/data/flight.db",
        "db_tables": {
            "flights": ["flight_id", "airline", "origin", "destination", "departure_time", "arrival_time", "price", "duration", "seat_availability"],
        },
    },
}
